=== RISCfuture/v303-mdc-generator/src/data/json/schemas/navaids.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://v303fg.com/schemas/navaids.schema.json",
  "title": "Navigation Aids Database",
  "description": "Navigation aid waypoints for DCS theaters with coordinates and elevations",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["name", "latitude", "longitude", "elevation"],
    "properties": {
      "name": {
        "type": "string",
        "description": "Navigation aid name/identifier"
      },
      "latitude": {
        "type": "number",
        "minimum": -90,
        "maximum": 90,
        "description": "Latitude in decimal degrees"
      },
      "longitude": {
        "type": "number",
        "minimum": -180,
        "maximum": 180,
        "description": "Longitude in decimal degrees"
      },
      "elevation": {
        "type": "number",
        "description": "Elevation in feet (from SRTM/NASA Digital Elevation Model)"
      }
    }
  }
}

=== RISCfuture/v303-mdc-generator/src/data/json/navaids/TheChannel.json
[
  {
    "name": "Abbeville",
    "latitude": 50.106083,
    "longitude": 1.833703,
    "elevation": 30
  },
  {
    "name": "Acheux-en-Amienois",
    "latitude": 50.072899,
    "longitude": 2.53062,
    "elevation": 469
  },
  {
    "name": "Acheux-en-Vimeu",
    "latitude": 50.064489,
    "longitude": 1.675123,
    "elevation": 312
  },
  {
    "name": "Acol",
    "latitude": 51.357756,
    "longitude": 1.311721,
    "elevation": 59
  },
  {
    "name": "Acq",
    "latitude": 50.348457,
    "longitude": 2.655962,
    "elevation": 308
  },
  {
    "name": "Acquet",
    "latitude": 50.22691,
    "longitude": 2.056536,
    "elevation": 207
  },
  {
    "name": "Acquin-Westbecourt",
    "latitude": 50.728756,
    "longitude": 2.089946,
    "elevation": 259
  },
  {
    "name": "Adinkerke",
    "latitude": 51.076216,
    "longitude": 2.598567,
    "elevation": 3
  },
  {
    "name": "Adisham",
    "latitude": 51.239153,
    "longitude": 1.188543,
    "elevation": 138
  },
  {
    "name": "Affringues",
    "latitude": 50.689861,
    "longitude": 2.074325,
    "elevation": 226
  },
  {
    "name": "Agenville",
    "latitude": 50.16507,
    "longitude": 2.10245,
    "elevation": 413
  },
  {
    "name": "Agenvillers",
    "latitude": 50.176756,
    "longitude": 1.917494,
    "elevation": 249
  },
  {
    "name": "Agnez-les-Duisans",
    "latitude": 50.30706,
    "longitude": 2.658735,
    "elevation": 243
  },
  {
    "name": "Agnieres",
    "latitude": 50.355059,
    "longitude": 2.607809,
    "elevation": 331
  },
  {
    "name": "Aigneville",
    "latitude": 50.033267,
    "longitude": 1.618383,
    "elevation": 374
  },
  {
    "name": "Ailly-le-Haut-Clocher",
    "latitude": 50.076495,
    "longitude": 1.992357,
    "elevation": 348
  },
  {
    "name": "Ailly-sur-Somme",
    "latitude": 49.928085,
    "longitude": 2.1981,
    "elevation": 89
  },
  {
    "name": "Airaines",
    "latitude": 49.96627,
    "longitude": 1.941064,
    "elevation": 105
  },
  {
    "name": "Aire-sur-la-Lys",
    "latitude": 50.639594,
    "longitude": 2.40006,
    "elevation": 79
  },
  {
    "name": "Airon-Notre-Dame",
    "latitude": 50.436507,
    "longitude": 1.655822,
    "elevation": 39
  },
  {
    "name": "Airon-Saint-Vaast",
    "latitude": 50.431377,
    "longitude": 1.669146,
    "elevation": 46
  },
  {
    "name": "Aix-en-Issart",
    "latitude": 50.475171,
    "longitude": 1.858967,
    "elevation": 75
  },
  {
    "name": "Albert",
    "latitude": 50.001802,
    "longitude": 2.650922,
    "elevation": 236
  },
  {
    "name": "Alembon",
    "latitude": 50.784734,
    "longitude": 1.887005,
    "elevation": 361
  },
  {
    "name": "Alette",
    "latitude": 50.51743,
    "longitude": 1.82726,
    "elevation": 108
  },
  {
    "name": "Alincthun",
    "latitude": 50.731247,
    "longitude": 1.803067,
    "elevation": 322
  },
  {
    "name": "Alkham",
    "latitude": 51.13574,
    "longitude": 1.223693,
    "elevation": 210
  },
  {
    "name": "Allenay",
    "latitude": 50.090232,
    "longitude": 1.49403,
    "elevation": 299
  },
  {
    "name": "Allery",
    "latitude": 49.96305,
    "longitude": 1.897986,
    "elevation": 118
  },
  {
    "name": "Allonville",
    "latitude": 49.939767,
    "longitude": 2.364224,
    "elevation": 344
  },
  {
    "name": "Allouagne",
    "latitude": 50.5325,
    "longitude": 2.50706,
    "elevation": 95
  },
  {
    "name": "Alquines",
    "latitude": 50.740526,
    "longitude": 1.992636,
    "elevation": 338
  },
  {
    "name": "Alveringem",
    "latitude": 51.011998,
    "longitude": 2.710503,
    "elevation": 26
  },
  {
    "name": "Ambleteuse",
    "latitude": 50.811233,
    "longitude": 1.606669,
    "elevation": 95
  },
  {
    "name": "Ambricourt",
    "latitude": 50.467973,
    "longitude": 2.175626,
    "elevation": 407
  },
  {
    "name": "Ambrines",
    "latitude": 50.310247,
    "longitude": 2.468694,
    "elevation": 420
  },
  {
    "name": "Ames",
    "latitude": 50.536715,
    "longitude": 2.408654,
    "elevation": 207
  },
  {
    "name": "Amettes",
    "latitude": 50.531129,
    "longitude": 2.39484,
    "elevation": 230
  },
  {
    "name": "Amiens",
    "latitude": 49.899546,
    "longitude": 2.295089,
    "elevation": 85
  },
  {
    "name": "Ancourt",
    "latitude": 49.910934,
    "longitude": 1.179063,
    "elevation": 115
  },
  {
    "name": "Andres",
    "latitude": 50.863969,
    "longitude": 1.914154,
    "elevation": 20
  },
  {
    "name": "Annezin",
    "latitude": 50.5415,
    "longitude": 2.6193,
    "elevation": 89
  },
  {
    "name": "Anvin",
    "latitude": 50.446435,
    "longitude": 2.252243,
    "elevation": 213
  },
  {
    "name": "Ardres",
    "latitude": 50.853632,
    "longitude": 1.978607,
    "elevation": 66
  },
  {
    "name": "Armbouts-Cappel",
    "latitude": 50.978044,
    "longitude": 2.351581,
    "elevation": 10
  },
  {
    "name": "Arneke",
    "latitude": 50.832041,
    "longitude": 2.411757,
    "elevation": 79
  },
  {
    "name": "Arques",
    "latitude": 50.739664,
    "longitude": 2.306207,
    "elevation": 33
  },
  {
    "name": "Arqueves",
    "latitude": 50.071686,
    "longitude": 2.469114,
    "elevation": 469
  },
  {
    "name": "Arras",
    "latitude": 50.288691,
    "longitude": 2.776158,
    "elevation": 243
  },
  {
    "name": "Arrest",
    "latitude": 50.126994,
    "longitude": 1.616619,
    "elevation": 85
  },
  {
    "name": "Arry",
    "latitude": 50.278391,
    "longitude": 1.720847,
    "elevation": 59
  },
  {
    "name": "Ash",
    "latitude": 51.280986,
    "longitude": 1.280306,
    "elevation": 75
  },
  {
    "name": "Ashford",
    "latitude": 51.148555,
    "longitude": 0.872257,
    "elevation": 194
  },
  {
    "name": "Attin",
    "latitude": 50.487875,
    "longitude": 1.743784,
    "elevation": 43
  },
  {
    "name": "Aubigny-en-Artois",
    "latitude": 50.351595,
    "longitude": 2.589628,
    "elevation": 308
  },
  {
    "name": "Aubin-Saint-Vaast",
    "latitude": 50.39766,
    "longitude": 1.974479,
    "elevation": 66
  },
  {
    "name": "Aubrometz",
    "latitude": 50.304194,
    "longitude": 2.17723,
    "elevation": 167
  },
  {
    "name": "Auchel",
    "latitude": 50.503749,
    "longitude": 2.468206,
    "elevation": 325
  },
  {
    "name": "Auchonvillers",
    "latitude": 50.081345,
    "longitude": 2.630008,
    "elevation": 486
  },
  {
    "name": "Auchy-au-Bois",
    "latitude": 50.555179,
    "longitude": 2.371047,
    "elevation": 299
  },
  {
    "name": "Auchy-les-Hesdin",
    "latitude": 50.398823,
    "longitude": 2.101955,
    "elevation": 112
  },
  {
    "name": "Audembert",
    "latitude": 50.861176,
    "longitude": 1.694268,
    "elevation": 223
  },
  {
    "name": "Audenfort",
    "latitude": 50.783137,
    "longitude": 1.97078,
    "elevation": 164
  },
  {
    "name": "Audincthun",
    "latitude": 50.582893,
    "longitude": 2.143174,
    "elevation": 322
  },
  {
    "name": "Audinghen",
    "latitude": 50.852665,
    "longitude": 1.61432,
    "elevation": 194
  },
  {
    "name": "Audrehem",
    "latitude": 50.781378,
    "longitude": 1.989835,
    "elevation": 197
  },
  {
    "name": "Audresselles",
    "latitude": 50.824181,
    "longitude": 1.595736,
    "elevation": 46
  },
  {
    "name": "Audruicq",
    "latitude": 50.878649,
    "longitude": 2.075236,
    "elevation": 23
  },
  {
    "name": "Ault",
    "latitude": 50.101564,
    "longitude": 1.447301,
    "elevation": 72
  },
  {
    "name": "Aumerval",
    "latitude": 50.506482,
    "longitude": 2.399188,
    "elevation": 430
  },
  {
    "name": "Autheux",
    "latitude": 50.14258,
    "longitude": 2.22862,
    "elevation": 479
  },
  {
    "name": "Authie",
    "latitude": 50.120757,
    "longitude": 2.489984,
    "elevation": 282
  },
  {
    "name": "Autingues",
    "latitude": 50.842121,
    "longitude": 1.985072,
    "elevation": 85
  },
  {
    "name": "Auxi-le-Chateau",
    "latitude": 50.231491,
    "longitude": 2.117761,
    "elevation": 121
  },
  {
    "name": "Avekapelle",
    "latitude": 51.066764,
    "longitude": 2.733326,
    "elevation": 7
  },
  {
    "name": "Averdoingt",
    "latitude": 50.34397,
    "longitude": 2.44161,
    "elevation": 489
  },
  {
    "name": "Avesnes",
    "latitude": 50.550698,
    "longitude": 1.969351,
    "elevation": 492
  },
  {
    "name": "Avesnes-en-Val",
    "latitude": 49.920193,
    "longitude": 1.398231,
    "elevation": 361
  },
  {
    "name": "Avesnes-le-Comte",
    "latitude": 50.276202,
    "longitude": 2.5277,
    "elevation": 433
  },
  {
    "name": "Avondance",
    "latitude": 50.476049,
    "longitude": 2.098952,
    "elevation": 417
  },
  {
    "name": "Avroult",
    "latitude": 50.633519,
    "longitude": 2.146319,
    "elevation": 449
  },
  {
    "name": "Aylesford",
    "latitude": 51.303717,
    "longitude": 0.482638,
    "elevation": 30
  },
  {
    "name": "Azincourt",
    "latitude": 50.463383,
    "longitude": 2.128827,
    "elevation": 394
  },
  {
    "name": "Bailleul",
    "latitude": 50.739667,
    "longitude": 2.734929,
    "elevation": 157
  },
  {
    "name": "Bailleul-aux-Cornailles",
    "latitude": 50.37133,
    "longitude": 2.44323,
    "elevation": 466
  },
  {
    "name": "Bailleul-les-Pernes",
    "latitude": 50.510004,
    "longitude": 2.3876,
    "elevation": 371
  },
  {
    "name": "Bailleulmont",
    "latitude": 50.215951,
    "longitude": 2.612239,
    "elevation": 459
  },
  {
    "name": "Bailleulval",
    "latitude": 50.22124,
    "longitude": 2.634088,
    "elevation": 387
  },
  {
    "name": "Baincthun",
    "latitude": 50.710464,
    "longitude": 1.680928,
    "elevation": 131
  },
  {
    "name": "Bainghen",
    "latitude": 50.752865,
    "longitude": 1.907283,
    "elevation": 410
  },
  {
    "name": "Baizieux",
    "latitude": 49.992474,
    "longitude": 2.51896,
    "elevation": 407
  },
  {
    "name": "Bajus",
    "latitude": 50.421067,
    "longitude": 2.481147,
